---
title: "ChromSSE models"
output: html_document
date: "2023-02-03"
---

Attempting to run the example in the original paper using the carex dataset
```{r}
# Set up RevBayes in RStudio
library(Revticulate)
knitRev()
```

# Run RevBayes code with rb code chunks
```{rb}
variable <- "Hi there! Welcome to RevBayes! I am now going to read in some test data."
variable
```

```{rb}
# Read in the tree
psi <- readTrees("ChromoSSE-master/examples/carex/data/phylo.tree")[1]
```



```{rb}
use_python("/usr/local/bin/python3", required = T)
```

Limit the maximum number of chromosomes, so here we just use the largest chromosome count plus 10:
```{rb}
max_chromo = 49
```

Get the observed chromosome counts from a tab-delimited file
```{rb}
chromo_data = readCharacterDataDelimited("ChromoSSE-master/examples/carex/data/chromosome_count.tsv", 
                                         stateLabels = (max_chromo + 1), 
                                         type = "NaturalNumbers", 
                                         delimiter = "\t")

```

# Here we set the expected number of anagenetic events used for prior mean.
# We use 2 expected events over the phylogeny, but you may want to test 
# for prior sensitivity. For very large trees with many expected chromosome 
# changes this value should be increased.
```{rb}
ana_events = 2
```

# Here we set the probability of sampling species at the present.
# We artificially use 1.0, but you can experiment with more realistic settings:
```{rb}
rho_bd = 1.0
phi = 1.0
```

# Set the total number of MCMC iterations to run:
```{rb}
mcmc_iterations = 5500
```

# Set the number of iterations to exclude as burnin:
```{rb}
burnin = 500
```

# Set the number of iterations to sample from MCMC:
```{rb}
sample_freq = 1
```

# Now run the ChromoSSE analysis:
```{rb}
source("ChromoSSE-master/ChromoSSE.Rev")
```

```{rb}


```
