---
title: "Visualising the data on the phylogeny"
author: "Natalie Cooper"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(here)
library(phytools)
library(ggtree)
library(ggnewscale)
library(patchwork)
```

Read in the data and the tree
```{r, message = FALSE, echo = FALSE}
mydata <- read_csv(here("data/chromosome-data-species.csv"))
mytree <- read.tree(here("data/Bayesian-tree-species.tre"))

# look at the dataset and tree
#str(mytree)
#head(mydata)
```

Extract some subsets of the data for the plotting
```{r}
# chromon
chromon <-
  mydata %>%
  select(haploidn) %>%
  as.data.frame()
# Add rownames as species names  
rownames(chromon) <- mydata$Binomial

# armn
arms <-
  mydata %>%
  select(armn) %>%
  as.data.frame()
# Add rownames as species names  
rownames(arms) <- mydata$Binomial

# macro pairs
macropairs <-
  mydata %>%
  select(macrop) %>%
  as.data.frame()
# Add rownames as species names  
rownames(macropairs) <- mydata$Binomial

# micro pairs
micropairs <-
  mydata %>%
  select(microp) %>%
  as.data.frame()
# Add rownames as species names  
rownames(micropairs) <- mydata$Binomial
```

Set up colour palettes

```{r}
mycolours <- c("grey", "#208EA3", "#FD817D", "#4178BC", "#EA4E9D",
                "#EECC16", "#E8384F", "black", "#E37CFF", "#37A862","#A4C61A","#7A71F6")
```

## Visualising data on the tree

Make trees using ggtree. Note that this code will throw lots of warnings about scales which can be ignored
```{r}
# Reorder data so it is the same order as the tree tip labels
mydata <- mydata[match(mytree$tip.label, mydata$tips), ]
# Replace tips with Binomials
mytree$tip.label <- mydata$Binomial

# create list of colours for genera
grp2 <- list(Bradypodion = c(mydata$Binomial[mydata$genus == "Bradypodion"]), 
            Brookesia = c(mydata$Binomial[mydata$genus == "Brookesia"]), 
            Calumma = c(mydata$Binomial[mydata$genus == "Calumma"]), 
            Chamaeleo = c(mydata$Binomial[mydata$genus == "Chamaeleo"]), 
            Furcifer = c(mydata$Binomial[mydata$genus == "Furcifer"]), 
            Kinyongia = c(mydata$Binomial[mydata$genus == "Kinyongia"]), 
            Palleon = c(mydata$Binomial[mydata$genus == "Palleon"]), 
            Rhampholeon = c(mydata$Binomial[mydata$genus == "Rhampholeon"]),
            Rieppeleon = c(mydata$Binomial[mydata$genus == "Rieppeleon"]),
            Trioceros = c(mydata$Binomial[mydata$genus == "Trioceros"]),
            outgroup = c(mydata$Binomial[mydata$genus == "Leiolepis"])) 

# Make the circular tree base
circ <- ggtree(mytree, layout = "circular") + geom_tiplab(size = 2, fontface = 3) + xlim(0, 200)

# Plot colours for genera
groupOTU(circ, grp2, 'Genus') + aes(color = Genus) +
  scale_colour_manual(values = mycolours) +
  theme(legend.position = "none")

# Save tree
# ggsave(filename = here("outputs/trees-genera-colour.png"), height = 5)
```

Add the chromosome data...
```{r}
# Make the circular tree base
circ <- ggtree(mytree, layout = "circular")

# Plot trees
p1 <- 
  gheatmap(circ, chromon, offset =.8, width =.2, colnames = FALSE) +
  scale_fill_viridis_c(na.value = "grey90", option = "plasma", name = "") +
  ggtitle("chromosomes (n)") +
  theme(plot.title = element_text(hjust = 0.5))
# Look at this
#p1

p2 <- 
  gheatmap(circ, arms, offset = .8, width =.2, colnames = FALSE) +
  scale_fill_viridis_c(na.value = "grey90", option = "magma", name = "") +
  ggtitle("arm number") +
  theme(plot.title = element_text(hjust = 0.5))
# Look at it
#p2

p3 <- 
  gheatmap(circ, macropairs, offset = .8, width =.2, colnames = FALSE) +
  scale_fill_viridis_c(na.value = "grey90", name = "") +
  ggtitle("macrochromosome pairs") +
  theme(plot.title = element_text(hjust = 0.5))
# Look at it
#p3

p4 <- 
  gheatmap(circ, micropairs, offset = .8, width =.2, colnames = FALSE) +
  scale_fill_viridis_c(na.value = "grey90", name = "") +
  ggtitle("microchromosome pairs") +
  theme(plot.title = element_text(hjust = 0.5))
# Look at it
#p4

(p1 + p2) / (p3 + p4)

# Save the plot
#ggsave(filename = here("outputs/trees-chromosome-properties.png"))

```