---
title: "Generic level variability"
author: "Natalie Cooper"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(here)
library(ape)
```

Read in the data and the tree
```{r, message = FALSE, echo = FALSE}
mydata <- read_csv(here("data/chromosome-data.csv"))
mytree <- read.tree(here("data/ML-tree.tre"))
```

Take a look at the dataset and tree
```{r}
#str(mytree)
#head(mydata)
```

Group by genera and get standard deviation for each variable
```{r}
data_genera <- 
  mydata %>%
  group_by(genus) %>%
  summarise_at(c("haploidn", "armn", "macrop", "microp", "Latitude", 
                 "maxSVL","minClutchSize", "maxClutchSize", "minBreedingAge",
                 "maxBreedingAge"), sd, na.rm = TRUE)

# Remove outgroup
data_genera <- filter(data_genera, genus != "Leiolepis")

a <-
  ggplot(data_genera, aes(x = maxSVL, y = haploidn, colour = genus)) +
  geom_point()

b <-
  ggplot(data_genera, aes(x = Latitude, y = haploidn, colour = genus)) +
  geom_point()

c <-
  ggplot(data_genera, aes(x = maxClutchSize, y = haploidn, colour = genus)) +
  geom_point()

d <- 
  ggplot(data_genera, aes(x = minBreedingAge, y = haploidn, colour = genus)) +
  geom_point()

library(patchwork)
(a + b) / (c + d)
```