---
title: "Are n=18 chameleons special?"
author: "Natalie Cooper"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(here)
library(ape)
library(patchwork)
```

Read in the data and the tree
```{r, message = FALSE, echo = FALSE}
mydata <- read_csv(here("data/chromosome-data.csv"))
mytree <- read.tree(here("data/ML-tree.tre"))
```

Take a look at the dataset and tree
```{r}
#str(mytree)
#head(mydata)
```

Add two characters to express haploid number is 18 or not, and 18/17 or not
```{r}
mydata <- mydata %>%
  mutate(n18 = case_when(haploidn == 18 ~ "n=18",
                         haploidn != 18 ~ "Not n=18")) %>%
  mutate(n1718 = case_when(haploidn == 17 ~ "n=17/n=18",
                         haploidn == 18 ~ "n=17/n=18",
                         haploidn != 18 & haploidn != 17 ~ "Not n=17/n=18"))
```

Make some plots to see if there is anything "special" about chameleons with n = 18 or 17.

```{r}
p1 <- 
  ggplot(mydata, aes(x = n18, y = maxSVL)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") +
  theme(legend.position = "none")

p2 <- ggplot(mydata, aes(x = n1718, y = maxSVL)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") 

p1 + p2
```

```{r}
p1 <- 
  ggplot(mydata, aes(x = n18, y = abs(Latitude))) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") +
  theme(legend.position = "none")

p2 <- ggplot(mydata, aes(x = n1718, y = abs(Latitude))) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") 

p1 + p2
```

```{r}
p1 <- 
  ggplot(mydata, aes(x = n18, y = minClutchSize)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") +
  theme(legend.position = "none")

p2 <- ggplot(mydata, aes(x = n1718, y = minClutchSize)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") 

p1 + p2
```

```{r}
p1 <- 
  ggplot(mydata, aes(x = n18, y = maxClutchSize)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") +
  theme(legend.position = "none")

p2 <- ggplot(mydata, aes(x = n1718, y = maxClutchSize)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") 

p1 + p2
```

```{r}
p1 <- 
  ggplot(mydata, aes(x = n18, y = minBreedingAge)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") +
  theme(legend.position = "none")

p2 <- ggplot(mydata, aes(x = n1718, y = minBreedingAge)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") 

p1 + p2
```

```{r}
p1 <- 
  ggplot(mydata, aes(x = n18, y = maxBreedingAge)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") +
  theme(legend.position = "none")

p2 <- ggplot(mydata, aes(x = n1718, y = maxBreedingAge)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") 

p1 + p2
```

```{r}
gp <- mydata %>%
  group_by(n18, Realm) %>% 
  tally() %>% 
  complete(Realm, fill = list(n = 0)) %>% 
  mutate(percentage = n / sum(n) * 100)

gp2 <- mydata %>%
  group_by(n1718, Realm) %>% 
  tally() %>% 
  complete(Realm, fill = list(n = 0)) %>% 
  mutate(percentage = n / sum(n) * 100)

p1 <- 
  ggplot(gp, aes(x = n18, y = percentage, fill = Realm)) +
  geom_bar(stat = 'identity', position = 'stack') +
  theme_bw() +
  xlab("chromosome number (n)") +
  theme(legend.position = "none")

p2 <-   
  ggplot(gp2, aes(x = n1718, y = percentage, fill = Realm)) +
  geom_bar(stat = 'identity', position = 'stack') +
  theme_bw() +
  xlab("chromosome number (n)")

p1 + p2
```

```{r}
gp <- mydata %>%
  group_by(n18, Substrate) %>% 
  tally() %>% 
  complete(Substrate, fill = list(n = 0)) %>% 
  mutate(percentage = n / sum(n) * 100)

gp2 <- mydata %>%
  group_by(n1718, Substrate) %>% 
  tally() %>% 
  complete(Substrate, fill = list(n = 0)) %>% 
  mutate(percentage = n / sum(n) * 100)

p1 <- 
  ggplot(gp, aes(x = n18, y = percentage, fill = Substrate)) +
  geom_bar(stat = 'identity', position = 'stack') +
  theme_bw() +
  xlab("chromosome number (n)") +
  theme(legend.position = "none")

p2 <-   
  ggplot(gp2, aes(x = n1718, y = percentage, fill = Substrate)) +
  geom_bar(stat = 'identity', position = 'stack') +
  theme_bw() +
  xlab("chromosome number (n)")

p1 + p2
```
```{r}
gp <- mydata %>%
  group_by(n18, Repromode) %>% 
  tally() %>% 
  complete(Repromode, fill = list(n = 0)) %>% 
  mutate(percentage = n / sum(n) * 100)

gp2 <- mydata %>%
  group_by(n1718, Repromode) %>% 
  tally() %>% 
  complete(Repromode, fill = list(n = 0)) %>% 
  mutate(percentage = n / sum(n) * 100)

p1 <- 
  ggplot(gp, aes(x = n18, y = percentage, fill = Repromode)) +
  geom_bar(stat = 'identity', position = 'stack') +
  theme_bw() +
  xlab("chromosome number (n)") +
  theme(legend.position = "none")

p2 <-   
  ggplot(gp2, aes(x = n1718, y = percentage, fill = Repromode)) +
  geom_bar(stat = 'identity', position = 'stack') +
  theme_bw() +
  xlab("chromosome number (n)")

p1 + p2

```

What about chromosome morphology?
  
```{r}
gp <- mydata %>%
  group_by(n18, norpos) %>% 
  tally() %>% 
  complete(norpos, fill = list(n = 0)) %>% 
  mutate(percentage = n / sum(n) * 100)

gp2 <- mydata %>%
  group_by(n1718, norpos) %>% 
  tally() %>% 
  complete(norpos, fill = list(n = 0)) %>% 
  mutate(percentage = n / sum(n) * 100)

p1 <- 
  ggplot(gp, aes(x = n18, y = percentage, fill = norpos)) +
  geom_bar(stat = 'identity', position = 'stack') +
  theme_bw() +
  xlab("chromosome number (n)") +
  theme(legend.position = "none")

p2 <-   
  ggplot(gp2, aes(x = n1718, y = percentage, fill = norpos)) +
  geom_bar(stat = 'identity', position = 'stack') +
  theme_bw() +
  xlab("chromosome number (n)")

p1 + p2
```


```{r}
p1 <- 
  ggplot(mydata, aes(x = n18, y = armn)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") +
  theme(legend.position = "none")

p2 <- ggplot(mydata, aes(x = n1718, y = armn)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") 

p1 + p2
```

```{r}
p1 <- 
  ggplot(mydata, aes(x = n18, y = macrop)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") +
  theme(legend.position = "none")

p2 <- ggplot(mydata, aes(x = n1718, y = macrop)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") 

p1 + p2
```

```{r}
p1 <- 
  ggplot(mydata, aes(x = n18, y = microp)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") +
  theme(legend.position = "none")

p2 <- ggplot(mydata, aes(x = n1718, y = microp)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") 

p1 + p2
```

```{r}
p1 <- 
  ggplot(mydata, aes(x = n18, y = norpair)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") +
  theme(legend.position = "none")

p2 <- ggplot(mydata, aes(x = n1718, y = norpair)) +
  geom_boxplot(fill = NA) +
  geom_jitter(aes(colour = genus), width = 0.1) +
  theme_bw() +
  xlab("chromosome number (n)") 

p1 + p2
```